# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventsFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EventsFeed
  pod 'Alamofire', '~> 5.4'
  pod 'SDWebImage', '~> 5.0'

  target 'EventsFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventsFeedUITests' do
    # Pods for testing
  end

end
